[tool.poetry]
name = "powerview"
version = "2024.0.0"
description = "Python based PowerView script"
authors = [
    "Aniq Fakhrul <aniqfakhrull@gmail.com>"
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/aniqfakhrul/powerview.py"
homepage = "https://github.com/aniqfakhrul/powerview.py"
classifiers = [
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
python = "^3.10"
impacket = { git = "https://github.com/ThePorgs/impacket.git" }
ldap3 = { git = "https://github.com/H0j3n/ldap3.git", branch = "powerview.py_match-requirements" }
dnspython = "*"
future = "*"
gnureadline = "*"
validators = "*"
dsinternals = "*"
chardet = "*"
tabulate = "*"
prompt-toolkit = "^3.0.43"
pygments = "^2.17.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
powerview = "powerview:main"
